### PR TITLE
Integrate BigDecimal_div and BigDecimal_div2

### LINKED ISSUE #220: "ERROR(VpDivd): space for remainder too small" for certain division
When upgrading to Ruby 3.1, I noticed a crashing edge-case when dividing by a certain number. It does not happen for bigdecimal < 3.1.1, but its 100% reproducible on 3.1.1.

The reproduction code is simple:

```ruby
BigDecimal('1.0') / BigDecimal('3672577333.6608990499165058135986328125')
```

Happens on both linux and macos.

```
irb(main):001:0> BigDecimal::VERSION
=> "3.1.1"
irb(main):002:0> BigDecimal('63.0') / BigDecimal('3672577333.6608990499165058135986328125')
(irb):2: [BUG] ERROR(VpDivd): space for remainder too small.
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0034 p:---- s:0198 e:000197 CFUNC  :/
c:0033 p:0012 s:0193 e:000192 EVAL   (irb):2 [FINISH]
c:0032 p:---- s:0190 e:000189 CFUNC  :eval
c:0031 p:0020 s:0182 e:000181 METHOD /usr/local/lib/ruby/3.0.0/irb/workspace.rb:116
c:0030 p:0059 s:0174 e:000172 METHOD /usr/local/lib/ruby/3.0.0/irb/context.rb:450
```

Further debug info is I think irrelevant, but I can attach if needed.

### PR DESCRIPTION
**Pull request by tompng**
Fixes #220, #222 and #272

BigDecimal_div and BigDecimal_div2 both have rounding problem (#272 and #328)
Integrating two division logic will make it easy to fix them.

Precision calculation for `a / b` and `a.div(b, 0)`  is improved. There is no exponential precision growth anymore.

### CODE REVIEW

File: ext/bigdecimal/bigdecimal.c [hunk 1]
```diff
@@ -2199,33 +2148,39 @@ BigDecimal_div2(VALUE self, VALUE b, VALUE n)
...
+        ix = ((a_prec > b_prec) ? a_prec : b_prec) + BIGDECIMAL_DOUBLE_FIGURES;
+        if (2 * BIGDECIMAL_DOUBLE_FIGURES > ix)
+            ix = 2 * BIGDECIMAL_DOUBLE_FIGURES;
+    }
+
+    // VpDivd needs 2 extra DECDIGs. One more is needed for rounding.
+    GUARD_OBJ(cv, NewZeroWrapLimited(1, ix + 3 * VpBaseFig()));
+
+    mx = bv->Prec + cv->MaxPrec - 1;
+    if (mx <= av->Prec) mx = av->Prec + 1;
```
Comment (tompng) [inline ext/bigdecimal/bigdecimal.c:2178]: Correct allocation size calculation of res.
VpDivd requires `word_a < word_r && word_b + word_c - 2 < word_r`

File: ext/bigdecimal/bigdecimal.c [hunk 2]
```diff
@@ -6164,7 +6119,7 @@ VpDivd(Real *c, Real *r, Real *a, Real *b)
     word_c = c->MaxPrec;
     word_r = r->MaxPrec;
 
-    if (word_a >= word_r) goto space_error;
+    if (word_a >= word_r || word_b + word_c - 2 >= word_r) goto space_error;
```
Comment (tompng) [inline ext/bigdecimal/bigdecimal.c:6122]: There are two more `goto space_error` in this function.
One is on [L6218](https://github.com/ruby/bigdecimal/blob/07facd4f2c14346ec72755df3eab57ec3a15c28f/ext/bigdecimal/bigdecimal.c#L6218)
```c
ind_r = ind_c + ind_b;
if (ind_r >= word_r) goto space_error;
```
And another in [L6253](https://github.com/ruby/bigdecimal/blob/07facd4f2c14346ec72755df3eab57ec3a15c28f/ext/bigdecimal/bigdecimal.c#L6253)
```c
ind_r = b->Prec + ind_c - 1; // L6242
ind_r = b->Prec + ind_c; // L6250 (ind_c + 1 < word_c is ensured in L6247)
if (ind_r >= word_r) goto space_error;
```
Both has the same requirement: `(word_b-1) + (word_c-1) < word_r`

File: test/bigdecimal/test_bigdecimal.rb [hunk 3]
```diff
@@ -510,10 +510,10 @@ def test_round_up
 
     BigDecimal.mode(BigDecimal::ROUND_MODE, BigDecimal::ROUND_HALF_DOWN)
     assert_operator(n4, :>, n4 / 9 * 9)
-    assert_operator(n5, :>, n5 / 9 * 9)
+    assert_operator(n5, :<, n5 / 9 * 9)
```
Comment (tompng) [inline test/bigdecimal/test_bigdecimal.rb:513]: Half down rules are:
```
123.5 → 123 (half down)
123.50001 → 124 (round up because it's larger than half)
0.55550 → 0.555
0.55551 → 0.556
0.55555555.. → 0.556 (Because it's larger than half)
```

In master branch, rounding of `BigDecimal#/` was inconsistent.
```ruby
BigDecimal.mode(BigDecimal::ROUND_MODE, BigDecimal::ROUND_HALF_DOWN)

BigDecimal(10)/BigDecimal('18')
#=> 0.555555555555555555555555555555555555e0 (ends with 5)
BigDecimal(1)/BigDecimal('1.8')
#=> 0.555555555555555555555555555555555556e0 (ends with 6)
```
